#
# Qxlnt
#

language: c++
compiler: gcc
sudo: require
dist: trusty # Ubuntu Xenial 16.04, Trusty 14.04, Precise 12.04

before_install:
  
  # C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 

  # C++17
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

  # Qt5
  - sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
  - sudo apt-get install qt5-default qttools5-dev-tools qtbase5-private-dev  

script:

  # test
  - g++ --version
  - cd Qxlnt.tests
  - qmake Qxlnt.test.pro
  - make
  - ./Qxlnt.test

# travis encrypt b903d8864201ee09c7099005ca3a5bf9f25a6418

#addons:
  #sonarcloud:
    #organization: "qtexcel"
    #token:
      #secure: "b903d8864201ee09c7099005ca3a5bf9f25a6418" # encrypted value of your token

#script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  #- sonar-scanner





